function pt_write_table(T, base, spec)
% pt_write_table - Write one results table as .csv, .txt and .tex
%
% Every table in the chapter pipeline goes through this function, so they
% share one layout: the CSV carries every column of T at full precision,
% the TXT and TEX carry the columns listed in spec, in that order and format.
%
% USAGE:
%   pt_write_table(T, base, spec)
%
% INPUT:
%   T     - MATLAB table
%   base  - output path WITHOUT extension, e.g. fullfile(d, 'within_types')
%   spec  - struct:
%             .cols     {n x 4} cell: {variable, txt header, tex header, fmt}
%                       fmt is a sprintf format, or 'p' for a p-value
%                       ('<0.001' below 0.001), or 'ci' to print
%                       "median [lo, hi]" from variables <var>, <var>_ci_lo
%                       and <var>_ci_hi.
%             .title    first line of the TXT file
%             .notes    {cellstr} lines printed under the TXT title
%             .caption  LaTeX caption
%             .label    LaTeX label
%             .group_by (optional) variable name; a \midrule and an italic
%                       heading are inserted wherever its value changes
%             .tex_rows (optional) logical [height(T) x 1] selecting the rows
%                       that reach the LaTeX table (CSV/TXT always get all)
%
% NOTES:
%   - NaN prints as '--'.
%   - The TEX output needs \usepackage{booktabs}.
%
% -------------------------------------------------------------------------
% Copyright (c) 2026 University College London
% Department of Imaging Neuroscience
%
% Author: Maike Schmidt
% Email:  maike.schmidt.23@ucl.ac.uk

out_dir = fileparts(base);
if ~isempty(out_dir) && ~exist(out_dir, 'dir'), mkdir(out_dir); end

writetable(T, [base '.csv']);

if height(T) == 0
    return
end

cols  = spec.cols;
n_col = size(cols, 1);
if ~isfield(spec, 'notes'),    spec.notes = {};   end
if ~isfield(spec, 'group_by'), spec.group_by = ''; end
if ~isfield(spec, 'tex_rows') || isempty(spec.tex_rows)
    spec.tex_rows = true(height(T), 1);
end

% Format every cell once, then lay out both text outputs from the strings
S = cell(height(T), n_col);
for r = 1:height(T)
    for c = 1:n_col
        S{r, c} = fmt_cell(T, r, cols{c, 1}, cols{c, 4});
    end
end

% ---- TXT ----------------------------------------------------------------
w = zeros(1, n_col);
for c = 1:n_col
    w(c) = max([numel(cols{c, 2}), cellfun(@numel, S(:, c))']);
end

fid = fopen([base '.txt'], 'w');
fprintf(fid, '%s\n', spec.title);
fprintf(fid, 'Generated: %s\n', char(datetime('now')));
for k = 1:numel(spec.notes)
    fprintf(fid, '%s\n', spec.notes{k});
end
fprintf(fid, '\n');
line = '';
for c = 1:n_col
    line = [line sprintf('%-*s  ', w(c), cols{c, 2})]; %#ok<AGROW>
end
fprintf(fid, '%s\n%s\n', line, repmat('-', 1, numel(line)));
prev = '';
for r = 1:height(T)
    if ~isempty(spec.group_by)
        g = group_value(T, r, spec.group_by);
        if ~strcmp(g, prev)
            if r > 1, fprintf(fid, '\n'); end
            fprintf(fid, '[%s]\n', g);
            prev = g;
        end
    end
    line = '';
    for c = 1:n_col
        line = [line sprintf('%-*s  ', w(c), S{r, c})]; %#ok<AGROW>
    end
    fprintf(fid, '%s\n', line);
end
fclose(fid);

% ---- TEX ----------------------------------------------------------------
fid = fopen([base '.tex'], 'w');
fprintf(fid, '%% Generated by msg_pert (pt_write_table), %s\n', char(datetime('now')));
fprintf(fid, '\\begin{table}[htbp]\n\\centering\n\\small\n');
fprintf(fid, '\\caption{%s}\n', spec.caption);
fprintf(fid, '\\label{%s}\n', spec.label);
fprintf(fid, '\\begin{tabular}{%s}\n\\toprule\n', ...
    ['l' repmat('r', 1, n_col - 1)]);
fprintf(fid, '%s \\\\\n\\midrule\n', strjoin(cols(:, 3)', ' & '));
prev = '';
first = true;
for r = find(spec.tex_rows(:))'
    if ~isempty(spec.group_by)
        g = group_value(T, r, spec.group_by);
        if ~strcmp(g, prev)
            if ~first, fprintf(fid, '\\midrule\n'); end
            fprintf(fid, '\\multicolumn{%d}{l}{\\textit{%s}} \\\\\n', ...
                n_col, tex_escape(g));
            prev = g;
        end
    end
    cells = cellfun(@tex_escape, S(r, :), 'UniformOutput', false);
    fprintf(fid, '%s \\\\\n', strjoin(cells, ' & '));
    first = false;
end
fprintf(fid, '\\bottomrule\n\\end{tabular}\n\\end{table}\n');
fclose(fid);
end


function s = fmt_cell(T, r, var, fmt)
    switch fmt
        case 'ci'
            m  = T.(var)(r);
            lo = T.([var '_ci_lo'])(r);
            hi = T.([var '_ci_hi'])(r);
            if isnan(m)
                s = '--';
            elseif isnan(lo)
                s = sprintf('%.3g', m);
            else
                s = sprintf('%.3g [%.3g, %.3g]', m, lo, hi);
            end
        case 'p'
            v = T.(var)(r);
            if isnan(v),        s = '--';
            elseif v < 0.001,   s = '<0.001';
            else,               s = sprintf('%.3f', v);
            end
        otherwise
            v = T.(var)(r);
            if iscell(v), v = v{1}; end
            if isstring(v), v = char(v); end
            if isnumeric(v) || islogical(v)
                if isnan(v), s = '--'; else, s = sprintf(fmt, v); end
            else
                s = sprintf(fmt, v);
            end
    end
end

function g = group_value(T, r, var)
    g = T.(var)(r);
    if iscell(g), g = g{1}; end
    if isnumeric(g), g = num2str(g); end
    g = char(g);
end

function s = tex_escape(s)
    s = strrep(s, '\', '\textbackslash{}');
    s = strrep(s, '_', '\_');
    s = strrep(s, '%', '\%');
    s = strrep(s, '&', '\&');
    s = strrep(s, '#', '\#');
    s = strrep(s, '<', '$<$');
    s = strrep(s, '>', '$>$');
    s = strrep(s, '^2', '$^2$');
end
